
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://kelsos.net"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /

# Google tracking id

google-tracking-id: "UA-34909088-2"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Konstantinos Paparas"
title: "Konstantinos Paparas (Kelsos)"
description: "Website of Konstantinos Paparas, Software Developer."
keywords: "kelsos, konstantinos, paparas, portfolio"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/background.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Everything is theoretically impossible, until it is done. - Robert A. Heinlein"

me-img: "/img/author.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "http-kelsos-net"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/brainbot.jpg"
    date: "Jul 2018 - Jul 2020"
    description: "Software Engineer"
    organization: "brainbot technologies AG"
  - image: "/img/timeline/arxnet.png"
    date: "Mar 2015 - Jul 2018"
    description: "Senior Android developer"
    organization: "arx.net s.a"
  - image: "/img/timeline/teithess.png"
    date: "Feb 2014"
    description: "Bachelor's degree<br/>Information Technology"
    organization: "ATEI Thessalonikis"
  - image: "/img/timeline/arxnet.png"
    date: "Apr 2013 - Jan 2014"
    description: "Front end developer"
    organization: "arx.net s.a"
  - image: "/img/timeline/arxnet.png"
    date: "Oct 2012 - Apr 2013"
    description: "Intern"
    organization: "arx.net s.a"
  - image: "/img/timeline/perfectedge.png"
    date: "Oct 2011 - May 2013"
    description: "System administrator<br/>Software developer"
    organization: "Perfect Edge Ltd"
  - image: "/img/timeline/teithess.png"
    date: "Oct 2004"
    description: "Studying<br/>Information Technology"
    organization: "ATEI Thessalonikis"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

############
# Projects #
############

projects:
  - title: "Rotki"
    image: "/img/projects/rotki_banner.png"
    description: "A portfolio tracking, analytics, accounting and tax reporting application that respects your privacy"
    url: "https://rotki.com"
  - title: "Raiden"
    image: "/img/projects/raiden.png"
    description: "Fast, cheap, scalable token transfers for Ethereum"
    url: "https://raiden.network"
  - title: "Sikorka"
    image: "/img/projects/sikorka_logo_site.png"
    description: "The Sikorka android application"
    url: "https://github.com/Sikorkaio/android-app/"
  - title: "MusicBee Remote"
    image: "/img/projects/mbremote_banner.png"
    description: "Android application for controlling remotely the MusicBee applications."
    url: "http://kelsos.net/musicbeeremote"
  - title: "White Mobile Cloud"
    image: "/img/projects/wmc_image.png"
    description: "Responsible for the android client as my main focus in arx.net s.a."
    url: "http://whitemobilecloud.com"
  - title: "MusicBee Skype Plugin"
    image: "/img/projects/mbskypenp.png"
    description: "Deprecated plugin that used the old Skype API to change the Skype mood to the playing track."
    url: "https://github.com/kelsos/mb-skype-plugin"
  - title: "Quote Backend"
    image: "/img/projects/opensource.png"
    description: "Simple php backend for storing retrieving quotes, uses <a href=\"http://www.slimframework.com/\">Slim</a> and <a href=\"http://propelorm.org/\">ProperlORM</a>."
    url: "https://github.com/kelsos/quote-backend"
  - title: "Quote Frontend"
    image: "/img/projects/opensource.png"
    description: "AngularJS 2 and Typescript base front end for the Quote site."
    url: "https://github.com/kelsos/quote-frontend"
  - title: "More Projects"
    image: "/img/projects/opensource.png"
    description: "You can find more of my opensource projects on GitHub."
    url: "https://github.com/kelsos"


###########
# Contact #
###########

email: "kelsos@kelsos.net"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Konstantinos Paparas is an Android developer that currently lives and works in Thessaloniki, Greece."
author_blurb_image: "/img/author.jpg"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/kelsos"
  - title: "twitter"
    url: "https://twitter.com/kelsos86"
  - title: "github"
    url: "https://github.com/kelsos"
  - title: "linkedin"
    url:  "https://gr.linkedin.com/in/kelsos"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: kelsos
keybase-in-social: True
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Projects: 'projects'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
